config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/users', to: 'users#list'
  get '/users/:id', to: 'users#show'
  get '/games/:id', to: 'games#show'
  post '/games/join', to: 'games#join'
  put '/games/:id', to: 'games#move'
  root to: 'users#index'

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :players
  has_many :users, through: :players

  validates_length_of :users, maximum: 2, message: "can have at most two players."

  serialize :board

  def self.waiting
    Game.where(:num_contestants => 1)
  end

  def self.active
    Game.where(:finished => false)
  end

  def self.contestants(id, number)
    self.update(id, :num_contestants => number)
  end

  def self.add_player2_email(id, email)
    self.update(id, :player2_email => email)
  end

  def self.add_to_turn_count(id)
    turns = (self.select('turn_count').where(:id => id).limit(1).first.turn_count) + 1
    self.update(id, :turn_count => turns)
  end

  def self.update_board(id, board)
    self.update(id, :board => board)
  end

  def can_move?(id, user_email)
    if self.turn_count.even?
      user_email == Game.select(:player2_email).where(:id => id).limit(1).first.player2_email
    else
      user_email == Game.select(:player1_email).where(:id => id).limit(1).first.player1_email
    end
  end

  def self.create_board(user_email)
    self.create(board: [[0, 0, 0, 0, 0, 0, 0], 
                        [0, 0, 0, 0, 0, 0, 0], 
                        [0, 0, 0, 0, 0, 0, 0], 
                        [0, 0, 0, 0, 0, 0, 0], 
                        [0, 0, 0, 0, 0, 0, 0], 
                        [0, 0, 0, 0, 0, 0, 0]], 
                        turn_count: 0, num_contestants: 1, player1_email: user_email, finished: false)
  end

  def self.game_state(game_id)
    self.select('id, board, turn_count').where(:id => game_id)
  end

  def self.existing_game(player_email)
    game = self.where("num_contestants = 2 AND player1_email = '#{player_email}'")
    if game.empty?
      game = self.where("num_contestants = 2 AND player2_email = '#{player_email}'")
    end
    game
  end
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :game, :counter_cache => true
  belongs_to :user

  validates_uniqueness_of :user_id, :scope => :game_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :players
  has_many :games, through: :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController

 def show

 end

  def join
    @user = current_user
    if @user.nil?
      flash[:alert] = 'You must be logged in to join a game.'
    else
      game = Game.waiting.all
      if game.empty?
        exist = Game.existing_game(@user.email).all
        if exist.empty?
          c4board = Game.create_board(@user.email)
          @board = c4board.board
          @welcome = "#{@user.email} is waiting for an opponent to join."
          @your_turn = true
          render :show
        else
          game = exist.first
          @welcome = "#{game.player1_email} VS. #{game.player2_email}"
          @board = Game.game_state(game.id)
          if (@board.first.turn_count.even?) && (@user.email == game.player2_email)
            @your_turn = true
          elsif (@board.first.turn_count.odd?) && (@user.email == game.player1_email)
            @your_turn = true
          end
          render :show
        end
      elsif (game.first.player1_email == @user.email) || (game.first.player2_email == @user.email)
        if game.first.player2_email.nil?
          @welcome = "#{@user.email} is waiting for an opponent to join."
        else
          @welcome = "#{game.first.player1_email} VS. #{game.first.player2_email}"
        end
        @board = Game.game_state(game.first.id)
        @your_turn = true if @board.first.turn_count == 0
        render :show
      elsif game.first.player2_email == @user.email
        @welcome = "#{game.first.player1_email} VS. #{game.first.player2_email}"
        @board = Game.game_state(game.first.id)
        @your_turn = true if @board.first.turn_count == 0
      else
        Game.add_player2_email(game.first.id, @user.email)
        Game.contestants(game.first.id, 2)
        game = Game.existing_game(@user.email).first
        @welcome = "#{game.player1_email} VS. #{@user.email}"
        @board = Game.game_state(game.id)
        @your_turn = true
        render :show
      end
    end
  end

  def move
    @user = current_user
    @game = Game.existing_game(@user.email).all.first
    @welcome = "#{@game.player1_email} VS. #{@game.player2_email}"
    @board = Game.game_state(@game.id)
    @your_turn = @game.can_move?(@game.id, @user.email)
    if @your_turn
      array = []
      [*0..5].each do |n|
        array << @board.first.board[n][params[:column].to_i]
      end
      position = nil
      [6, 5, 4, 3, 2, 1, 0].each do |n|
        if array[n] == 0
          position = n
          break
        end
      end
      if position.nil?
        render :show
      else
        new_board = @board.first.board
        if @game.player1_email == @user.email
          new_board[position][params[:column].to_i] = 1
        else
          new_board[position][params[:column].to_i] = 2
        end
        Game.update_board(@game.id, new_board)

        # Check for winning conditions here - add additional logic in board partial to handle a win

        Game.add_to_turn_count(@game.id)
        @your_turn = false
        render :show
      end
    else
      # Never reach here - page doesn't give player option to move if it isn't his or her turn
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    render :index
  end

  def list
    @users = User.select(:email).all
    render :list
  end

  def show
    render :sign_out
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_board.html.erb
<% if @your_turn %>
    <table>
      <tr>
        <% [*0..6].each do |n| %>
            <td><%= button_to "#{n}", "/games/#{n}", params: { :column => n }, :method => :put %></td>
        <% end %>
      </tr>
      <% @board.first.board.each do |row| %>
          <tr>
            <% row.each do |col| %>
                <% if col == 1 %>
                    <td><%= image_tag('Goku1.png') %></td>
                <% elsif col == 2 %>
                    <td><%= image_tag('Cell1.png') %></td>
                <% else %>
                    <td><%= image_tag('blank1.png') %></td>
                <% end %>
            <% end %>
          </tr>
      <% end %>
    </table>
<% else %>
    <h3>Waiting on opponent to take his or her turn.</h3>
    <table>
      <% @board.first.board.each do |row| %>
          <tr>
            <% row.each do |col| %>
                <% if col == 1 %>
                    <td><%= image_tag('Goku1.png') %></td>
                <% elsif col == 2 %>
                    <td><%= image_tag('Cell1.png') %></td>
                <% else %>
                    <td><%= image_tag('blank1.png') %></td>
                <% end %>
            <% end %>
          </tr>
      <% end %>
    </table>
<% end %>

app/views/games/show.html.erb
<h1>Connect Four Game Board</h1>
<h3><%= @welcome %></h3>

<% if @welcome.include?('VS.') %>
    <%= render 'games/board' %>
<% end %>

<br>
<div><%= link_to 'Back To User Page', root_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ConnectRails4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/_sign_out.html.erb
<%= link_to 'Users Page', users_path %>

app/views/users/index.html.erb
<h1>Connect Four</h1>
<% if current_user %>
    <h3>Welcome, <%= current_user.email %></h3>

    <%= link_to 'Join Game', games_join_path, method: :post %> |

    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>

<% else %>
    <%= render 'users/sign_out' %>
<% end %>

app/views/users/list.html.erb
<h1>Connect Four Users:</h1>

<% @users.each do |user| %>
    <h3><%= user.email %></h3>
<% end %>

<%= link_to 'Create New User', new_user_session_path %> |
<%= link_to 'Sign In', user_session_path %>